=== tc-amorevino/thomasaidancurran-com/src/.json-schemas/media-schema.json
{
  "type": "array",
  "items": {
    "type": "object",
    "properties": {
      "slug": {
        "type": "string",
        "minLength": 1
      },
      "title": {
        "type": "string",
        "minLength": 1
      },
      "publication": {
        "type": "string"
      },
      "format": {
        "type": "string",
        "enum": [
          "video",
          "article"
        ]
      },
      "image": {
        "type": "string"
      },
      "href": {
        "type": "string",
        "format": "uri"
      },
      "type": {
        "type": "string",
        "enum": [
          "interview",
          "panel",
          "commentary",
          "presentation"
        ]
      },
      "year": {
        "type": "integer",
        "minimum": 1000,
        "maximum": 9999
      }
    },
    "required": [
      "slug",
      "title",
      "format",
      "href",
      "type",
      "year"
    ],
    "additionalProperties": false
  },
  "$schema": "http://json-schema.org/draft-07/schema#"
}

=== tc-amorevino/thomasaidancurran-com/src/cms/media.json
[
  {
    "slug": "pre-dev-sovereign-ai-integration-with-nvidia-enterprise-ai-using-nvidias-gpu-h200-accelerated-infrastructure",
    "title": "pre.dev sovereign AI integration with Nvidia Enterprise AI using Nvidia's GPU H200 accelerated infrastructure",
    "publication": "pre.dev",
    "format": "video",
    "image": "./images/pre-dev-sovereign-ai-integration-with-nvidia-enterprise-ai-using-nvidias-gpu-h200-accelerated-infrastructure_814x458.png",
    "href": "https://www.youtube.com/watch?v=7-OhvUt6_OY",
    "type": "presentation",
    "year": 2025
  },
  {
    "slug": "scaling-ai-startups-overcoming-challenges-building-for-the-future",
    "title": "Scaling AI startups: Overcoming Challenges & Building for the Future",
    "publication": "NVIDIA GTC",
    "format": "video",
    "image": "./images/scaling-ai-startups-overcoming-challenges-building-for-the-future_300x168.jpg",
    "href": "https://www.nvidia.com/en-us/on-demand/session/gtc25-s74253/",
    "type": "panel",
    "year": 2025
  },
  {
    "slug": "ory-summit-2023-closing-remarks_",
    "title": "Ory Summit 2023 Closing Remarks",
    "publication": "Ory Summit",
    "format": "video",
    "image": "./images/ory-summit-2023-closing-remarks_720x404.avif",
    "href": "https://www.youtube.com/watch?v=V8rbWjYoZaM",
    "type": "presentation",
    "year": 2024
  },
  {
    "slug": "how-to-design-and-build-modern-open-source-software-in-go",
    "title": "How to design and build modern open source software in Go",
    "publication": "Google Developer Groups",
    "format": "video",
    "image": "./images/how-to-design-and-build-modern-open-source-software-in-go_299x168.jpg",
    "href": "https://www.youtube.com/watch?v=IWDlVSSdKC8",
    "type": "presentation",
    "year": 2023
  },
  {
    "slug": "how-the-ai-curse-could-become-a-blessing-for-journalism",
    "title": "How the AI curse could become a blessing for journalism",
    "publication": "Horizont Kongress (german)",
    "format": "article",
    "image": "./images/how-the-ai-curse-could-become-a-blessing-for-journalism_940x529.jpg",
    "href": "https://www.horizont.net/medien/nachrichten/horizont-kongress-wie-der-ki-fluch-fuer-den-journalismus-zum-segen-werden-koennte-213079",
    "type": "panel",
    "year": 2023
  },
  {
    "slug": "securing-the-digital-world",
    "title": "Securing the digital world",
    "publication": "Ory Summit",
    "format": "video",
    "image": "./images/securing-the-digital-world_480x270.avif",
    "href": "https://www.youtube.com/watch?v=wo7eZREQg9s",
    "type": "presentation",
    "year": 2022
  },
  {
    "slug": "cloud-security-provider-ory-corp-raises-22-million-in-series-a-round-led-by-insight-partners",
    "title": "Cloud-Security Provider Ory Corp Raises $22 Million in Series A Round Led by Insight Partners",
    "publication": "Insight Partners",
    "format": "article",
    "image": "./images/cloud-security-provider-ory-corp-raises-22-million-in-series-a-round-led-by-insight-partners_750x401.webp",
    "href": "https://www.insightpartners.com/ideas/cloud-security-provider-ory-corp-raises-22-million-in-series-a-round-led-by-insight-partners/",
    "type": "interview",
    "year": 2021
  },
  {
    "slug": "intersource-is-github-culture-and-open-source-principles",
    "title": "Intersource is GitHub culture and open source principles",
    "publication": "GitHub Satellite",
    "format": "video",
    "image": "./images/intersource-is-github-culture-and-open-source-principles_300x188.avif",
    "href": "https://www.youtube.com/watch?v=Kg3k_K65J5o",
    "type": "presentation",
    "year": 2019
  },
  {
    "slug": "cloud-migration-means-transformation-at-deutsche-boerse-group",
    "title": "Cloud Migration Means Transformation at Deutsche Börse Group",
    "publication": "AWS Summit",
    "format": "video",
    "image": "./images/cloud-migration-means-transformation-at-deutsche-boerse-group_720x404.avif",
    "href": "https://www.youtube.com/watch?v=jQzAKh8OcFE",
    "type": "presentation",
    "year": 2018
  },
  {
    "slug": "developer-platform-github-in-the-sign-of-the-octocat",
    "title": "Developer Platform GitHub: In the Sign of the Octocat",
    "publication": "Tagesspiegel (german)",
    "format": "article",
    "image": "./images/developer-platform-github-in-the-sign-of-the-octocat_1000x428.jpg",
    "href": "https://www.tagesspiegel.de/wirtschaft/im-zeichen-der-krakenkatze-5535355.html",
    "type": "commentary",
    "year": 2018
  },
  {
    "slug": "google-cloud-summit-munich-keynote",
    "title": "Google Cloud Summit Munich Keynote",
    "publication": "Google Cloud Summit",
    "format": "video",
    "image": "./images/google-cloud-summit-munich-keynote_600x300.webp",
    "href": "https://www.youtube.com/watch?v=sm3xLN0n95o&t=2910s",
    "type": "panel",
    "year": 2017
  },
  {
    "slug": "the-man-for-whom-the-deutsche-boerse-was-too-slow",
    "title": "The man for whom the Deutsche Börse was too slow (german)",
    "publication": "Welt (german)",
    "format": "article",
    "image": "./images/the-man-for-whom-the-deutsche-boerse-was-too-slow_300x168.jpg",
    "href": "https://www.welt.de/wirtschaft/plus169609106/Deutsche-Boerse-Thomas-Curran-digitalisiert-den-Konzern.html",
    "type": "interview",
    "year": 2017
  },
  {
    "slug": "silicon-valley-insider-this-development-is-set-to-decisively-change-your-daily-life",
    "title": "Silicon Valley Insider: This development is set to decisively change your daily life",
    "publication": "Welt (german)",
    "format": "article",
    "image": "./images/silicon-valley-insider-this-development-is-set-to-decisively-change-your-daily-life_2000x1333.png",
    "href": "https://www.welt.de/kmpkt/article170168893/Diese-Entwicklung-soll-deinen-Alltag-entscheidend-veraendern.html",
    "type": "commentary",
    "year": 2017
  },
  {
    "slug": "unlocking-iots-potential-in-open-education",
    "title": "Unlocking IOT's Potential in Open Education",
    "publication": "webit",
    "format": "video",
    "image": "./images/unlocking-iots-potential-in-open-education_480x270.avif",
    "href": "https://www.youtube.com/watch?v=AT6TBhfxYFc",
    "type": "presentation",
    "year": 2014
  },
  {
    "slug": "cto-design-challenge-privacy-vs-security-finding-a-technology-solution",
    "title": "CTO Design Challenge: Privacy vs. Security: Finding a Technology Solution",
    "publication": "FiRe: Future in Review",
    "format": "video",
    "image": "./images/cto-design-challenge-privacy-vs-security-finding-a-technology-solution_720x404.avif",
    "href": "https://www.youtube.com/watch?v=h2rXjqdQtTE",
    "type": "panel",
    "year": 2014
  },
  {
    "slug": "cto-design-challenge-scaling-alternative-energy-how-can-it-be-done",
    "title": "CTO Design Challenge: Scaling Alternative Energy: How Can It Be Done?",
    "publication": "FiRe: Future in Review",
    "format": "video",
    "image": "./images/cto-design-challenge-scaling-alternative-energy-how-can-it-be-done_336x188.avif",
    "href": "https://www.youtube.com/watch?v=V7sv9BSeYhc",
    "type": "panel",
    "year": 2010
  },
  {
    "slug": "broadband",
    "title": "Broadband",
    "publication": "DLD Conference",
    "format": "video",
    "image": "./images/broadband_336x188.avif",
    "href": "https://www.youtube.com/watch?v=fvoIi2ZOU8s",
    "type": "panel",
    "year": 2010
  },
  {
    "slug": "enquiry-commission-on-the-internet-and-digital-society",
    "title": "Enquiry Commission on the Internet and Digital Society",
    "publication": "German Bundestag (german)",
    "format": "video",
    "image": "./images/enquiry-commission-on-the-internet-and-digital-society_512x288.jpg",
    "href": "https://www.bundestag.de/webarchiv/textarchiv/2010/31564797_kw39_pa_internetenquete-202840",
    "type": "panel",
    "year": 2010
  }
]
