=== tc-amorevino/thomasaidancurran-com/src/.json-schemas/portfolio-schema.json
{
  "type": "array",
  "items": {
    "type": "object",
    "properties": {
      "slug": {
        "type": "string",
        "minLength": 1
      },
      "title": {
        "type": "string",
        "minLength": 1
      },
      "description": {
        "type": "string"
      },
      "image": {
        "type": "string"
      },
      "href": {
        "type": "string",
        "format": "uri"
      },
      "type": {
        "type": "string",
        "enum": [
          "advisor",
          "angel investor",
          "founder"
        ]
      }
    },
    "required": [
      "slug",
      "title",
      "href",
      "type"
    ],
    "additionalProperties": false
  },
  "$schema": "http://json-schema.org/draft-07/schema#"
}

=== tc-amorevino/thomasaidancurran-com/src/cms/portfolio.json
[
  {
    "slug": "voxist",
    "title": "Voxist",
    "description": "Enterprise ready, API-first voice-to-intelligence AI models",
    "image": "src/cms/images/voxist_840x840.jpg",
    "href": "https://www.voxist.com/",
    "type": "advisor"
  },
  {
    "slug": "aladdin",
    "title": "Aladdin",
    "description": "AI platform & humanoid infrastructure for urban waste management",
    "image": "src/cms/images/aladdin_840x840.jpg",
    "href": "https://aladdin.link/",
    "type": "advisor"
  },
  {
    "slug": "predev",
    "title": "pre.dev",
    "description": "AI Platform for software architecture and development scoping",
    "image": "src/cms/images/predev_840x840.jpg",
    "href": "https://pre.dev/",
    "type": "angel investor"
  },
  {
    "slug": "alembic",
    "title": "Alembic",
    "description": "AI for marketing analytics & intelligence",
    "image": "src/cms/images/alembic_840x840.jpg",
    "href": "https://getalembic.com/",
    "type": "angel investor"
  },
  {
    "slug": "amorevino",
    "title": "AMOREVINO",
    "description": "AI integrated product information management (PIM) platform for the wine industry",
    "image": "src/cms/images/amorevino_840x840.jpg",
    "href": "https://www.amorevino.com/",
    "type": "angel investor"
  },
  {
    "slug": "reversinglabs",
    "title": "ReversingLabs",
    "description": "Platform for software-supply-chain security analysis and threat detection.",
    "image": "src/cms/images/reversinglabs_840x840.jpg",
    "href": "https://www.reversinglabs.com/",
    "type": "advisor"
  },
  {
    "slug": "ory",
    "title": "Ory",
    "description": "Open-source & zero trust identity and access management platform",
    "image": "src/cms/images/ory_840x840.jpg",
    "href": "https://www.ory.sh/",
    "type": "founder"
  }
]
